script:
  - npm install
  - |
    while sleep 9m; do
      echo "====[ $SECONDS seconds still running ]===="
    done &
  - npm test
language: node_js
node_js:
  - 12
  - 14
os:
  - windows
  - linux
